server:
  port: 9008

spring:
  application:
    name: news-service
  data:
    mongodb:
      host: 68.183.244.52
      port: 27017
      database: nearly_events
      username: event_manager
      password: ChooseASecurePassword123!
      authentication-database: nearly_events
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

logging:
  file:
    name: logs/news-service.log

