server:
  port: 9017

spring:
  application:
    name: report-service
  data:
    mongodb:
      host: 68.183.244.52
      port: 27017
      database: nearly_events
      username: event_manager
      password: ChooseASecurePassword123!
      authentication-database: nearly_events
  elasticsearch:
    uris: http://68.183.244.194:9200
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: report-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

# Report categories
reports:
  categories:
    - harassment
    - inappropriate_content
    - spam
    - impersonation
    - other

logging:
  file:
    name: logs/report-service.log
